HvD: Previously when the "make realclean" failed the script would continue and tar-up a whole bunch of junk. Now the script will check whether the make was successfull and terminate the script if it was not successfull. That way it is obvious something went wrong.

diff --git a/contrib/distro-tools/build_nwchem_src_distro b/contrib/distro-tools/build_nwchem_src_distro
--- a/contrib/distro-tools/build_nwchem_src_distro
+++ b/contrib/distro-tools/build_nwchem_src_distro
@@ -82,6 +82,10 @@ svn revert ${target}/src/config/make_nwchem_config
 pushd ${target}/src
 export USE_RISKYFC=yes
 make -j 1 realclean                                         2>&1 > /dev/null
+if [ $? -ne 0 ] ; then
+  echo "Make failed. Aborting..."
+  exit 1
+fi
 popd
 if [ -d ${target}/lib ] ; then
   rm -rf ${target}/lib
