HvD: If the code was never built then do not try to run make realclean. This is usefull for Jenkins where the checkout happens on a platform where we never build the code. Jenkins just checks the code out and generates a tar-ball that is stored somewhere. Another build project will pull that tar-ball and build the code on a test platform. So there is no need to run the realclean when generating the tar-ball.

diff --git a/contrib/distro-tools/build_nwchem_src_distro b/contrib/distro-tools/build_nwchem_src_distro
--- a/contrib/distro-tools/build_nwchem_src_distro
+++ b/contrib/distro-tools/build_nwchem_src_distro
@@ -83,11 +83,13 @@ svn revert ${target}/src/config/make_nwchem_config
 pushd ${target}/src
 export USE_RISKYFC=yes
 export NWCHEM_MODULES=all
-make -j 1 nwchem_config                                     2>&1 > /dev/null
-make -j 1 realclean                                         2>&1 > /dev/null
-if [ $? -ne 0 ] ; then
-  echo "Make failed. Aborting..."
-  exit 1
+if [ -f config/nwchem_config.h ] ; then
+  make -j 1 nwchem_config                                     2>&1 > /dev/null
+  make -j 1 realclean                                         2>&1 > /dev/null
+  if [ $? -ne 0 ] ; then
+    echo "Make failed. Aborting..."
+    exit 1
+  fi
 fi
 unset NWCHEM_MODULES
 popd
