included Pawel's frame script for the documentation and updated the SCF, CCSD and MCSCF documentation to reality

diff --git a/doc/htmlize b/doc/htmlize
--- a/doc/htmlize
+++ b/doc/htmlize
@@ -9,7 +9,6 @@ if ($#argv != 1) then
   exit 1
 endif
 
-
 set WWWDIR=/msrc/doc/www/changes/docs/nwchem/doc
 set TMP=tmp.$$
 
@@ -25,6 +24,8 @@ foreach document ($1)
 # First make sure the latex builds OK
 
   echo "   Cleaning and making $document.ps"
+
+goto doit
 
   make clean >& /dev/null
   make $document.ps >& $document.latex.log
@@ -145,11 +146,38 @@ foreach document ($1)
     exit 1
   endif
 
+# Now run Pawel's magic perl script to make the frames
+doit:
+  if (! $?NWCHEM_TOP ) then
+    echo "   NWCHEM_TOP is not defined ... cannot generate frames"
+  else if (! -e $NWCHEM_TOP/doc/make_manual.pl) then
+    echo "   $NWCHEM_TOP/doc/make_manual.pl missing ... cannot generate frames"
+  else
+    echo "   Making frames"
+    pushd $WWWDIR/$document > /dev/null
+    if ($document == "user") then
+      set title = "NWChem User Manual"
+    else if ($document == "prog") then
+      set title = "NWChem Programmers Manual"
+    else
+      set title = "NWChem Manual"
+    endif
+
+    $NWCHEM_TOP/doc/make_manual.pl $document.html "$title"
+
+    if ($status != 0) then
+      echo "   Making the frames failed"
+    endif
+   
+    popd > /dev/null
+  endif
+
+
 # Hopefully all is OK
 
   echo "   Done with $document"
  
-  /bin/rm -f $TMP $document
+  /bin/rm -rf $TMP $document
 
 end
 
