check DOS files

diff --git a/src/config/64_to_32 b/src/config/64_to_32
--- a/src/config/64_to_32
+++ b/src/config/64_to_32
@@ -12,26 +12,33 @@ if [[ -z "${NWCHEM_TOP}" ]]; then
 fi
 pythonexe=python
 pythonscript=${NWCHEM_TOP}/src/config/64_to_32.py
+filecheck="/tmp/myfail.txt"
 
-
+rm -f $filecheck
  JOB_LIMIT=6
 
  njob=0
-
+ nfail=0
 for file in "$@"
 do
 if [ -f "$file" ]; then
    echo converting "$file" to 32-bit integers for BLAS/LAPACK
-      ($pythonexe $pythonscript $file) &	
+   ($pythonexe $pythonscript $file ; if [ $? == 123 ]; then echo $file> $filecheck;fi ) &
 
    let njob++
    if [ $njob -gt $JOB_LIMIT ]; then
      wait
      let njob=0
    fi
+else
+    echo "!!!!file missing: " "$file"
 fi
 done
-
 if [ $njob -gt  0 ] ; then
     wait
 fi
+if [  -f $filecheck ]; then
+    echo 'Error: DOS file '$(cat $filecheck)
+    exit 1
+fi
+    
