revert to git clone when tarball is not there

diff --git a/src/tools/get-tools-github b/src/tools/get-tools-github
--- a/src/tools/get-tools-github
+++ b/src/tools/get-tools-github
@@ -36,41 +36,44 @@ USE_GA_RELEASE=1
 fi
 if test "x$USE_GA_RELEASE" != x
 then
-if test "x$GA_RELEASE_NO" = x
-then
-    GA_RELEASE_NO=5.6.5
-fi
-    GA_DIR=ga-"$GA_RELEASE_NO"
-if [ ! -f ga-"$GA_RELEASE_NO".tar.gz ]; then
-TAR_URL=https://github.com/GlobalArrays/ga/releases/download/v"$GA_RELEASE_NO"/ga-"$GA_RELEASE_NO".tar.gz
-# TAR_URL=https://github.com/edoapra/ga/releases/download/v"$GA_RELEASE_NO"/ga-"$GA_RELEASE_NO".tar.gz
-#         https://github.com/edoapra/ga/releases/download/v5.6.5/ga-5.6.5.tar.gz
- echo "downloading" ga-"$GA_RELEASE_NO".tar.gz  "from" "$TAR_URL"
-  WGET_YES=`wget  -O 2>&1 | head -1  | awk ' /require/ {print "Y";exit};{print "N"}'`
-if [ $WGET_YES = "Y" ]
-then
- wget  -O ga-"$GA_RELEASE_NO".tar.gz "$TAR_URL"
-else
-#try curl because wget is not there
- curl -L  "$TAR_URL" -o ga-"$GA_RELEASE_NO".tar.gz
-fi
-    if [ $? -ne 0 ]
+    if test "x$GA_RELEASE_NO" = x
     then
-	rm -f ga-"$GA_RELEASE_NO".tar.gz
-	echo "wget failed for"  ga-"$GA_RELEASE_NO".tar.gz
-	echo " " 
-	exit 1
+	GA_RELEASE_NO=5.6.5
+    fi
+    GA_DIR=ga-"$GA_RELEASE_NO"
+    if [ ! -f ga-"$GA_RELEASE_NO".tar.gz ]; then
+	TAR_URL=https://github.com/GlobalArrays/ga/releases/download/v"$GA_RELEASE_NO"/ga-"$GA_RELEASE_NO".tar.gz
+	# TAR_URL=https://github.com/edoapra/ga/releases/download/v"$GA_RELEASE_NO"/ga-"$GA_RELEASE_NO".tar.gz
+	#         https://github.com/edoapra/ga/releases/download/v5.6.5/ga-5.6.5.tar.gz
+	echo "downloading" ga-"$GA_RELEASE_NO".tar.gz  "from" "$TAR_URL"
+	WGET_YES=`wget  -O 2>&1 | head -1  | awk ' /require/ {print "Y";exit};{print "N"}'`
+	if [ $WGET_YES = "Y" ]
+	then
+	    wget  -O ga-"$GA_RELEASE_NO".tar.gz "$TAR_URL"
+	else
+	    #try curl because wget is not there
+	    curl -L  "$TAR_URL" -o ga-"$GA_RELEASE_NO".tar.gz
+	fi
+	if [ $? -ne 0 ]
+	then
+	    rm -f ga-"$GA_RELEASE_NO".tar.gz
+	    echo "wget failed for"  ga-"$GA_RELEASE_NO".tar.gz
+	    echo "trying git clone"
+	    echo " "
+	    DEV_GA=1
+#	    exit 1
+	fi
+    fi
+    if [ ! -f ga-"$GA_RELEASE_NO".tar.gz ]; then 
+	echo "Failed to download" ga-$GA_RELEASE_NO.tar.gz
+	#    exit 1
+    else
+	if [ ! -f "$GA_DIR"/configure ]; then 
+	    tar xvzf ga-"$GA_RELEASE_NO".tar.gz
+	fi
     fi
 fi
-if [ ! -f ga-"$GA_RELEASE_NO".tar.gz ]; then 
-    echo "Failed to download" ga-$GA_RELEASE_NO.tar.gz
-    exit 1
-else
-if [ ! -f "$GA_DIR"/configure ]; then 
- tar xvzf ga-"$GA_RELEASE_NO".tar.gz
-fi
-fi
-else #USE_GA_RELEASE
+#oldelse #USE_GA_RELEASE
 if test "x$DEV_GA" != x
 then
 #DEV_GA=1 gives the current "best" dev branch, not develop
@@ -78,17 +81,17 @@ then
     GA_DIR=ga-5.6.5
     GA_BRANCH=hotfix/5.6.5
 else
-  if test "x$GA_BRANCH" != x
-  then
-    if test "x$GA_DIR" = x
+    if test "x$GA_BRANCH" != x
     then
-       GA_DIR0=ga-"$GA_BRANCH"
-       GA_DIR=`echo $GA_DIR0 | sed -e 's/\//_/g'`
+	if test "x$GA_DIR" = x
+	then
+	    GA_DIR0=ga-"$GA_BRANCH"
+	    GA_DIR=`echo $GA_DIR0 | sed -e 's/\//_/g'`
+	fi
+    else
+	GA_DIR=ga-5-6-5
+	GA_BRANCH=hotfix/5.6.5
     fi
-  else
-     GA_DIR=ga-5-6-5
-     GA_BRANCH=hotfix/5.6.5
-  fi
 fi
 if test "x$GA_URL" != x
 then
@@ -131,7 +134,7 @@ else
 	exit 1
     fi
 fi
-fi #USE_GA_RELEASE
+#fi #USE_GA_RELEASE
 # check if configure is there
 if test -e $GA_DIR/configure
 then
